test_dev_stack_deploy_steps: &test_dev_stack_deploy_steps
  steps:
    - run: echo "Triggering branch $TRIGGER_BRANCH"
    - run: |
        # these are all provided by circleci project settings > environment variables
        echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $BASH_ENV
        echo "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $BASH_ENV
    - checkout
    - attach_workspace:
        at: ~/demo_website

    - run:
        name: Deploy Stack
        command: |
          sudo apt-get install -y python-pip
          sudo pip install awscli
          cd ~/demo_website/cloudformation
          sh deploy.sh $INSTANCE


version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  deploy-test-dev:
    working_directory: ~/demo_website
    docker:
      - image: cimg/node:15.5.0
        environment:
          AWS_REGION: ap-south-1
          INSTANCE: preview
    <<: *test_dev_stack_deploy_steps

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-test-dev
